In [5]:
import numpy as np
import random

In [41]:
for i in range (1, 20):
    random_value=random.uniform(0, 1000)
    array=random_value*np.random.random_sample((i))
    print(array)
    
    #f(v)=const
    f=5
    
    #f(v)=∑_(k=1)^n▒v_k 
    summ=0
    for el in array:
        summ=summ+el
    print(summ)
        
    #f(v)=∏_(k=1)^n▒v_k 
    res=0
    flag=False
    for el in array:
        if flag==False:
            res=el
            flag=True
        else:
            res=res*el        
    print(res)
    
    #каждый элемент - коэфф. многочлена
    new_res=0
    for j in range (len(array)):
        new_res=new_res+array[j]*(1.5**(j-1))
    print(new_res)
    
    #quicksort
    def quick_sort(array):
        less = []
        equal = []
        greater = []
        if len(array) > 1:
            pivot = array[0]
            for x in array:
                if x < pivot:
                    less.append(x)
                elif x == pivot:
                    equal.append(x)
                elif x > pivot:
                    greater.append(x)
            return quick_sort(less)+equal+quick_sort(greater)
        else: 
            return array
    print(quick_sort(array))
    
    #timsort - стандартный для python
    print('timesort')
    print (sorted(array))
    
    #сортировка пузырьком
    def bubble_sort(bad_list):
        length = len(bad_list) - 1
        finished = False
        while not finished:
            finished = True
            for i in range(length):
                if bad_list[i] > bad_list[i+1]:
                    finished = False
                    bad_list[i], bad_list[i+1] = bad_list[i+1], bad_list[i]
    bubble_sort(array)
    print(array)
    
    

[511.99748105]
511.9974810544004
511.9974810544004
341.3316540362669
[511.99748105]
timesort
[511.9974810544004]
[511.99748105]
[ 61.80210911 144.50062438]
206.30273348610643
8930.44335392372
185.70203045037303
[61.80210910720022, 144.50062437890622]
timesort
[61.80210910720022, 144.50062437890622]
[ 61.80210911 144.50062438]
[ 59.99026868 111.6171527  274.89557602]
446.5029974103772
1840685.1026025284
563.9540291942558
[59.99026868277255, 111.61715270466577, 274.8955760229389]
timesort
[59.99026868277255, 111.61715270466577, 274.8955760229389]
[ 59.99026868 111.6171527  274.89557602]
[202.98025658  28.78667717 324.92326352 697.83734958]
1254.5275468503273
1324891613.8166308
2221.625780055462
[28.786677167281443, 202.98025658387698, 324.9232635211564, 697.8373495780125]
timesort
[28.786677167281443, 202.98025658387698, 324.9232635211564, 697.8373495780125]
[ 28.78667717 202.98025658 324.92326352 697.83734958]
[121.73293194 561.35778411 288.55951885 747.15715763 514.36303199]
2233.17042